### PR TITLE
color brackets by scope

### PR DESCRIPTION
**Pull request by mdequeljoe**
This pr proposes the addition of colored brackets in order to help distinguish between scopes. 

This is done by adding the entry: `bracket` to `default_style` whereby one can set the list of colouring functions to be used to color brackets.

An internal function `color_brackets` is added such that brackets are colored consecutively by the scope level according to the color sequence passed in via `bracket`. The following brackets are considered:

`[[` `[` `]` `(` `)` `{` `}`

Note that the counterpart of `[[` is two `]` characters instead of `]]` as this bracket would be parsed as an 'LBB' token (or as a 'SYMBOL_FUNCTION_CALL' and thus not passed on to `color_brackets`)
 Some more details are provided in the documentation.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Love this! I am in the middle of something, but will look at it later today. Thanks much!

**Comment by gaborcsardi** [comment]
Sorry, it took "a bit" longer in the end. :( I think this is great! Can you please add a bullet point to the NEWS, with your GH username and the PR id? Then I'll be most happy to merge it.

Thanks again!

**Comment by gaborcsardi** [comment]
You know what, don't worry about it, I'll do it....

Thanks again!

**Comment by gaborcsardi** [comment]
How could I live without this? I love this feature already.

**Comment by mdequeljoe** [comment]
great thanks!!

**Pull request merged**
